create table if not exists public.eye_sync_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role_name text not null check (role_name in ('developer','supremo','level1','level2','level3')),
  hotel_codes text[] not null default '{}',
  can_read_all boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.eye_sync_objects (
  id bigint generated by default as identity primary key,
  hotel_code text not null check (hotel_code in ('gio','choco','brigantino')),
  entity_type text not null,
  entity_uuid uuid not null,
  payload jsonb not null default '{}'::jsonb,
  source_device text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(entity_type, entity_uuid)
);

create index if not exists eye_sync_objects_hotel_idx on public.eye_sync_objects(hotel_code, entity_type, updated_at desc);
create index if not exists eye_sync_objects_updated_idx on public.eye_sync_objects(updated_at desc);
create index if not exists eye_sync_objects_updated_by_idx on public.eye_sync_objects(updated_by);
alter table public.eye_sync_memberships enable row level security;
alter table public.eye_sync_objects enable row level security;
revoke all on public.eye_sync_memberships from anon, authenticated;
revoke all on public.eye_sync_objects from anon, authenticated;
grant select on public.eye_sync_memberships to service_role;
grant all on public.eye_sync_objects to service_role;
grant usage, select on sequence public.eye_sync_objects_id_seq to service_role;
