import {ReactNode} from 'react';
import {LayoutDashboard,FileText,Package,Users,Upload,Sparkles,ChartNoAxesCombined,History,TriangleAlert,Tags,Settings,MonitorCog,Menu,X,ReceiptText,MessageSquareText} from 'lucide-react';

export type Page = 'dashboard'|'invoices'|'products'|'suppliers'|'import'|'ai'|'reports'|'history'|'anomalies'|'categories'|'settings'|'system';
const nav:[Page,string,any][]=[['dashboard','Dashboard',LayoutDashboard],['invoices','Fatture',FileText],['products','Prodotti',Package],['suppliers','Fornitori',Users],['import','Importa',Upload],['ai','Ricerca IA',Sparkles],['reports','Report',ChartNoAxesCombined],['history','Storico',History],['anomalies','Anomalie',TriangleAlert],['categories','Categorie',Tags],['settings','Impostazioni',Settings],['system','Sistema',MonitorCog]];
export function Shell({page,setPage,area,setArea,children,open,setOpen}:{page:Page,setPage:(p:Page)=>void,area:'invoices'|'reviews',setArea:(a:'invoices'|'reviews')=>void,children:ReactNode,open:boolean,setOpen:(v:boolean)=>void}){
 return <div className="app-shell">
  <aside className={`sidebar ${open?'open':''}`}><div className="brand"><b>RAND</b>{area==='invoices'?'FATTURE':'RECENSIONI'}<span>{area==='invoices'?'Le tue fatture, più valore.':'Ascolta, rispondi, migliora.'}</span></div><div className="area-switch" role="group" aria-label="Cambia area"><button className={area==='invoices'?'active':''} onClick={()=>setArea('invoices')}><ReceiptText/>Fatture</button><button className={area==='reviews'?'active':''} onClick={()=>setArea('reviews')}><MessageSquareText/>Recensioni</button></div>{area==='invoices'?<nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav>:<nav><button className="active"><LayoutDashboard size={19}/><span>Panoramica</span></button><button><MessageSquareText size={19}/><span>Tutte le recensioni</span></button><button><Sparkles size={19}/><span>Analisi IA</span></button><button><Settings size={19}/><span>Impostazioni</span></button></nav>}<div className="local-status"><i/>{area==='invoices'?'Archivio locale':'Recensioni locali'}<small>Windows · Offline first</small></div></aside>
  {open&&<button className="scrim" aria-label="Chiudi menu" onClick={()=>setOpen(false)}/>}<main><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{children}</main>
 </div>
}
