import {useEffect,useState} from 'react';
import {KeyRound,Power,Users} from 'lucide-react';
import {currentUser,eyeApi} from '../lib/api';
import {Status} from './UI';

type User={id:number;username:string;display_name:string;role_name:string;pin_configured:boolean;active:boolean};

export function UserAdmin(){
 const [users,setUsers]=useState<User[]>([]),[pins,setPins]=useState<Record<number,string>>({}),[message,setMessage]=useState(''),[newUser,setNewUser]=useState({username:'',display_name:'',role_name:'supremo',pin:'000000'});
 const load=()=>eyeApi<User[]>('/auth/users').then(setUsers);
 useEffect(()=>{load().catch(()=>{})},[]);
 async function save(user:User){const pin=pins[user.id]||'';if(pin.length<6){setMessage('Il PIN deve avere almeno 6 cifre.');return}try{await eyeApi(`/auth/users/${user.id}/pin`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});setPins({...pins,[user.id]:''});setMessage(`PIN aggiornato per ${user.display_name}`);await load()}catch(e:any){setMessage(e.message)}}
 async function create(){if(!newUser.username||!newUser.display_name||newUser.pin.length<6){setMessage('Compila username, nome e un PIN di almeno 6 cifre.');return}try{await eyeApi('/auth/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(newUser)});setMessage(`Utente ${newUser.display_name} creato`);setNewUser({username:'',display_name:'',role_name:'supremo',pin:'000000'});await load()}catch(e:any){setMessage(e.message)}}
 async function toggleActive(user:User){try{await eyeApi(`/auth/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!user.active})});setMessage(`${user.display_name} ${user.active?'disattivato':'riattivato'}`);await load()}catch(e:any){setMessage(e.message)}}
 const actor=currentUser();
 return <section className="panel user-admin-panel"><div className="panel-title"><div><h2><Users size={18}/> Utenti locali e PIN</h2><span>Accesso operativo unificato · PIN sempre mascherati</span></div><Status tone="ok">{users.filter(u=>u.active).length} attivi</Status></div><p>Tutti i profili hanno gli stessi permessi. Il PIN standard iniziale è 000000 e può essere cambiato in qualsiasi momento.</p>{message&&<p className="settings-message">{message}</p>}<div className="preview-grid"><label>Username<input value={newUser.username} onChange={e=>setNewUser({...newUser,username:e.target.value})} placeholder="es. reception"/></label><label>Nome visualizzato<input value={newUser.display_name} onChange={e=>setNewUser({...newUser,display_name:e.target.value})} placeholder="Nome e cognome"/></label><label>PIN iniziale<input inputMode="numeric" type="password" maxLength={12} value={newUser.pin} onChange={e=>setNewUser({...newUser,pin:e.target.value.replace(/\D/g,'')})} placeholder="000000"/></label></div><div className="form-actions"><button className="primary-btn" onClick={create}>Crea utente</button></div><div className="table-wrap"><table><thead><tr><th>Utente</th><th>Stato</th><th>PIN</th><th>Accesso</th><th>Azioni</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className={!u.active?'user-inactive':''}><td><b>{u.display_name}</b><small style={{display:'block'}}>{u.username}</small></td><td><Status tone={u.active?'ok':'warn'}>{u.active?'Attivo':'Disattivato'}</Status></td><td><input aria-label={`Nuovo PIN ${u.display_name}`} inputMode="numeric" type="password" maxLength={12} value={pins[u.id]||''} onChange={e=>setPins({...pins,[u.id]:e.target.value.replace(/\D/g,'')})} placeholder="Nuovo PIN"/><small className="pin-state">{u.pin_configured?'PIN configurato':'PIN da configurare'}</small></td><td><Status tone="ok">Completo</Status></td><td className="user-actions"><button className="secondary-btn" onClick={()=>save(u)} disabled={!u.active}><KeyRound size={15}/>Salva PIN</button><button className="secondary-btn" onClick={()=>toggleActive(u)} disabled={u.id===actor?.id}><Power size={15}/>{u.active?'Disattiva':'Riattiva'}</button></td></tr>)}</tbody></table></div></section>;
}
