import {useMemo,useState,useEffect} from 'react';
import {ArrowDown,ArrowRight,ArrowUp,Printer,Search,MapPin,RotateCcw} from 'lucide-react';
import {api,eyeApi,euro,shortDate} from '../lib/api';
import {Empty,Loading,PageHeader,SearchBox,Status} from '../components/UI';
import './historical-report.css';

type Point={date:string;price:number;quantity?:number|null;delta:number|null;delta_pct:number|null;trend:'initial'|'up'|'down'|'same';unit:string;invoice:string;description:string};
type SupplierBlock={supplier_id:number;supplier:string;unit:string;manufacturer:string|null;initial_price:number;initial_date:string;average_price:number;best_price:number;best_date:string;latest_price:number;latest_date:string;observations:number;points:Point[]};
type Report={query:string;summary:any;suppliers:SupplierBlock[];dates:string[];units:string[];comparison_note:string;matches?:Array<{canonical_name:string;canonical_names?:string[];brand?:string|null;purchases?:number;avg_price?:number|null}>};

type Suggestion={nome_canonico:string;canonical_names?:string[];purchases?:number;avg_price?:number|null;marca?:string|null;unita_base?:string|null};
function HistorySearch({value,onChange,onSearch,disabled,closeSignal,placeholder}:{value:string;onChange:(value:string)=>void;onSearch:(value?:string)=>void;disabled?:boolean;closeSignal?:number;placeholder:string}){
 const [items,setItems]=useState<Suggestion[]>([]),[open,setOpen]=useState(false),[completionEnabled,setCompletionEnabled]=useState(true);
 useEffect(()=>{if(disabled){setOpen(false);setCompletionEnabled(false)}},[disabled]);
 useEffect(()=>{setOpen(false)},[closeSignal]);
 useEffect(()=>{let active=true;const query=value.trim();if(query.length<2){setItems([]);return}const timer=window.setTimeout(async()=>{try{const result=await api<Suggestion[]>(`/products?q=${encodeURIComponent(query)}&limit=8`);if(active&&!disabled){setItems(result.slice(0,8));setOpen(true)}}catch{if(active)setItems([])}},220);return()=>{active=false;window.clearTimeout(timer)}},[value,disabled]);
 return <div className="hist-autocomplete"><SearchBox value={value} onChange={v=>{onChange(v);setCompletionEnabled(true);setOpen(true)}} onEnter={()=>{setOpen(false);setCompletionEnabled(false);onSearch()}} placeholder={placeholder}/>{completionEnabled&&open&&value.trim().length>=2&&items.length>0&&<div className="hist-suggestions" role="listbox" aria-label="Suggerimenti prodotto">{items.map(item=>{const searchValue=item.nome_canonico.toLowerCase()==='acqua'?'acqua':item.canonical_names?.[0]||item.nome_canonico;return <button type="button" role="option" key={item.nome_canonico} onMouseDown={e=>e.preventDefault()} onClick={()=>{setOpen(false);setCompletionEnabled(false);onChange(item.nome_canonico);onSearch(searchValue)}}><b>{item.nome_canonico}</b><small>{item.marca||'Prodotto'}{item.purchases!=null?` · ${item.purchases} acquisti`:''}{item.avg_price!=null?` · media normalizzata ${euro(Number(item.avg_price))}${item.unita_base?`/${item.unita_base}`:''}`:''}</small></button>})}</div>}</div>
}

function Trend({point}:{point?:Point}){if(!point)return <span className="hist-empty">—</span>;const Icon=point.trend==='up'?ArrowUp:point.trend==='down'?ArrowDown:ArrowRight;return <div className={`hist-price ${point.trend}`}><b>{euro(point.price)}</b>{point.quantity!=null&&<em>{point.quantity} {point.unit}</em>}<small><Icon size={12}/>{point.delta===null?'iniziale':`${point.delta>0?'+':''}${point.delta.toFixed(2)} €${point.delta_pct===null?'':` · ${point.delta_pct>0?'+':''}${point.delta_pct.toFixed(1)}%`}`}</small></div>}

export function HistoricalReportPage({embedded=false}:{embedded?:boolean}){
 const [q,setQ]=useState(''),[submitted,setSubmitted]=useState(''),[data,setData]=useState<Report>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [supplierSort,setSupplierSort]=useState<'average'|'best'|'latest'|'name'>('average'),[dateDirection,setDateDirection]=useState<'asc'|'desc'>('asc');
 async function search(nextQuery=q){const value=nextQuery.trim();if(!value)return;setQ(value);setBusy(true);setError('');setSubmitted(value);setData(undefined);try{setData(await eyeApi<Report>(`/reports/history-product?q=${encodeURIComponent(value)}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function clear(){setQ('');setSubmitted('');setData(undefined);setError('');}
 const comparable=useMemo(()=>data?.summary?data.suppliers.filter(s=>s.unit===data.summary.unit):[],[data]);
 const sortedSuppliers=useMemo(()=>[...comparable].sort((a,b)=>supplierSort==='name'?a.supplier.localeCompare(b.supplier):supplierSort==='best'?a.best_price-b.best_price:supplierSort==='latest'?a.latest_price-b.latest_price:a.average_price-b.average_price),[comparable,supplierSort]);
 const sortedMatches=useMemo(()=>data?.matches?[...data.matches].sort((a,b)=>{const pieces=(x:string)=>Number((x.match(/(?:^|\s)(\d+)\s*(?:pz|pezzi|pcs|bott)/i)||[])[1]||0);return pieces(a.canonical_name)-pieces(b.canonical_name)||a.canonical_name.localeCompare(b.canonical_name)}):[],[data]);
 // Keep one continuous matrix: suppliers are listed once and all purchases
 // remain horizontally scrollable instead of being duplicated on each page.
 const pages=useMemo(()=>data?.dates?.length?[dateDirection==='asc'?data.dates:[...data.dates].reverse()]:[],[data,dateDirection]);
 const totalObservations=useMemo(()=>comparable.reduce((total,s)=>total+s.observations,0),[comparable]);
 return <><div className="screen-only">{!embedded&&<PageHeader title="Report storico" subtitle="Prodotto → produttore/marca → fornitore → andamento prezzi"><div className="hist-search"><HistorySearch value={q} onChange={setQ} onSearch={search} disabled={busy} placeholder="Cerca prodotto…"/><button className="primary-btn" onClick={()=>search()} disabled={busy||!q.trim()}><Search size={16}/>{busy?'Cerco…':'Cerca'}</button>{(q||data)&&<button className="secondary-btn" onClick={clear} disabled={busy}><RotateCcw size={16}/>Azzera</button>}{data?.summary&&<button className="secondary-btn" onClick={()=>window.print()}><Printer size={16}/>Stampa / PDF</button>}</div></PageHeader>}{embedded&&<div className="hist-search"><HistorySearch value={q} onChange={setQ} onSearch={search} disabled={busy} placeholder="Cerca prodotto nello storico…"/><button className="primary-btn" onClick={()=>search()} disabled={busy||!q.trim()}><Search size={16}/>{busy?'Cerco…':'Cerca'}</button>{(q||data)&&<button className="secondary-btn" onClick={clear} disabled={busy}><RotateCcw size={16}/>Azzera</button>}{data?.summary&&<button className="secondary-btn" onClick={()=>window.print()}><Printer size={16}/>Stampa / PDF</button>}</div>}{error&&<div className="error">{error}</div>}{busy&&<Loading/>}{!busy&&!submitted&&!data&&<section className="panel hist-start"><Search size={25}/><h2>Cerca un prodotto</h2><p>Inserisci una descrizione, una marca o un prodotto per vedere prezzi, fornitori e variazioni nel tempo.</p></section>}</div>
  {!busy&&submitted&&data&&!data.summary&&<section className="panel screen-only">{data.matches?.length?<><div className="panel-title"><h2>Seleziona il prodotto</h2><span className="muted">Varianti equivalenti raggruppate per contenuto</span></div><div className="history-matches">{sortedMatches.map(item=><button key={item.canonical_name} className="history-match" onClick={()=>search(item.canonical_names?.[0] || item.canonical_name)}><b>{item.canonical_name}</b><small>{item.purchases??0} acquisti{item.avg_price!=null?` · media ${euro(Number(item.avg_price))}`:''}</small></button>)}</div></>:<Empty title="Nessuno storico trovato" text={`Nessun acquisto prodotto trovato per “${submitted}”.`}/>}</section>}
 {data?.summary&&<div className="history-report" id="history-report-print">
   <section className="hist-summary screen-only">
    <article><span>Prezzo iniziale</span><strong>{euro(data.summary.initial_price)}</strong><small>{shortDate(data.summary.initial_date)}</small></article>
    <article><span>Prezzo medio</span><strong>{euro(data.summary.average_price)}</strong><small>per {data.summary.unit}</small></article>
    <article><span>Miglior prezzo</span><strong>{euro(data.summary.best_price)}</strong><small>{shortDate(data.summary.best_date)}</small></article>
    <article><span>Ultimo prezzo</span><strong>{euro(data.summary.latest_price)}</strong><small>{shortDate(data.summary.latest_date)}</small></article>
    <article className="best"><span>Fornitore più conveniente</span><strong>{data.summary.best_supplier}</strong><small>media {euro(data.summary.best_supplier_average)} · {data.summary.best_supplier_observations} rilevazioni</small></article>
   </section>
   <div className="screen-only hist-note"><b>{data.summary.product}</b>{data.summary.manufacturers?.length?<span>Produttore/Marca: {data.summary.manufacturers.join(', ')}</span>:<span>Produttore/Marca da associare</span>}<Status tone="ok">unità confronto: {data.summary.unit}</Status><span>{comparable.length} fornitori · {totalObservations} rilevazioni · {data.dates.length} date</span><small>{data.comparison_note}</small></div>
   <div className="screen-only hist-controls"><label>Fornitori<select value={supplierSort} onChange={e=>setSupplierSort(e.target.value as typeof supplierSort)}><option value="average">media più bassa</option><option value="best">miglior prezzo</option><option value="latest">ultimo prezzo</option><option value="name">nome A–Z</option></select></label><label>Date<select value={dateDirection} onChange={e=>setDateDirection(e.target.value as typeof dateDirection)}><option value="asc">dalla più vecchia</option><option value="desc">dalla più recente</option></select></label><span className="muted">— = nessun acquisto in quella data</span></div>
   {pages.map((datePage,pageIndex)=><section className="print-sheet" key={pageIndex}>
    <header className="print-header"><div><b>EYE SUPREMO · REPORT STORICO</b><h1>{data.summary.product}</h1><p>Produttore/Marca: {data.summary.manufacturers?.join(', ')||'da associare'} · Unità: {data.summary.unit}</p></div><div className="print-kpis"><span>Iniziale <b>{euro(data.summary.initial_price)}</b></span><span>Media <b>{euro(data.summary.average_price)}</b></span><span>Migliore <b>{euro(data.summary.best_price)}</b></span><span>Ultimo <b>{euro(data.summary.latest_price)}</b></span><span>Fornitore migliore <b>{data.summary.best_supplier}</b></span></div></header>
    <div className="matrix-direction" aria-label="Direzione tabella">Fornitori ↓ <span>·</span> acquisti / date →</div><div className="hist-matrix-scroll"><table className="hist-matrix"><caption className="sr-only">Confronto prezzi storici per fornitore e data</caption><thead><tr><th className="supplier-col">Fornitore</th><th className="maker-col">Produttore / Marca</th>{datePage.map(d=><th key={d}>{shortDate(d)}</th>)}</tr></thead><tbody>{sortedSuppliers.map(s=><tr key={`${s.supplier_id}-${s.unit}`}><th>{s.supplier}<small>iniz. {euro(s.initial_price)} · media {euro(s.average_price)} · best {euro(s.best_price)} · ultimo {euro(s.latest_price)}</small></th><td>{s.manufacturer||'—'}</td>{datePage.map(d=>{const point=s.points.find(p=>p.date===d);return <td key={d} title={point?.description||data.summary.product}>{<Trend point={point}/>}</td>})}</tr>)}</tbody></table></div>
    <footer>Scheda prodotto {pageIndex+1}/{pages.length} · tutti i fornitori sono confrontati nella stessa matrice.</footer>
   </section>)}
  </div>}
 </>;
}

type Destination={id:number;number:string;date:string;supplier:string;total:number;destination:string|null;destination_name:string};
type Hotel={id:number;code:string;name:string};
export function InvoiceDestinationsPage(){const [items,setItems]=useState<Destination[]>(),[hotels,setHotels]=useState<Hotel[]>([]),[q,setQ]=useState('');const load=()=>eyeApi<Destination[]>('/invoice-destinations').then(setItems);useEffect(()=>{Promise.all([load(),eyeApi<Hotel[]>('/hotels').then(setHotels)])},[]);async function change(id:number,hotel_code:string){await eyeApi(`/invoice-destinations/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({hotel_code})});await load()}const visible=items?.filter(x=>(`${x.number} ${x.supplier} ${x.destination_name}`).toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Destinazione fattura" subtitle="Le fatture sono uniche per Apice; qui indichi solo la destinazione/centro di utilizzo"><SearchBox value={q} onChange={setQ} placeholder="Fattura, fornitore, destinazione…"/></PageHeader><section className="panel list-panel">{!visible?<Loading/>:visible.length?<div className="table-wrap"><table><thead><tr><th>Data</th><th>Fattura</th><th>Fornitore</th><th>Totale</th><th>Destinazione</th></tr></thead><tbody>{visible.map(i=><tr key={i.id}><td>{shortDate(i.date)}</td><td><b>{i.number}</b></td><td>{i.supplier}</td><td>{euro(i.total)}</td><td><label className="destination-select"><MapPin size={14}/><select value={i.destination||'general'} onChange={e=>change(i.id,e.target.value)}><option value="general">Generale / Apice</option>{hotels.map(h=><option key={h.code} value={h.code}>{h.name}</option>)}</select></label></td></tr>)}</tbody></table></div>:<Empty title="Nessuna fattura" text="Le fatture importate compariranno qui per l'assegnazione facoltativa della destinazione."/>}</section></>}
