import {useEffect,useMemo,useRef,useState} from 'react';
import {MessageSquareText,Star,Search,UploadCloud,Trophy,TriangleAlert} from 'lucide-react';
import {PageHeader,Status} from '../components/UI';
import {currentUser,eyeApi} from '../lib/api';

type Hotel={id:number;code:string;name:string};
type Review={id:number;hotel:string;hotel_code:string;room:string|null;author:string|null;source:string|null;rating:number|null;date:string;text:string;tags:{category:string;polarity:string;confidence:number}[]};
type Ranking={best_rooms:any[];worst_rooms:any[];best_services:any[];worst_services:any[]};

export default function Reviews(){
 const user=currentUser(); const canSeeAll=user?.role_name==='developer'||user?.role_name==='supremo';
 const [hotels,setHotels]=useState<Hotel[]>([]),[hotel,setHotel]=useState(canSeeAll?'all':''),[query,setQuery]=useState(''),[reviews,setReviews]=useState<Review[]>([]),[rank,setRank]=useState<Ranking>({best_rooms:[],worst_rooms:[],best_services:[],worst_services:[]}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const input=useRef<HTMLInputElement>(null);
 const selected=hotels.find(h=>h.code===hotel);
 const load=async()=>{const hotelParam=hotel&&hotel!=='all'?`?hotel_code=${hotel}`:'';const [r,k]=await Promise.all([eyeApi<Review[]>(`/reviews${hotelParam}`),eyeApi<Ranking>(`/rankings${hotelParam}`)]);setReviews(r);setRank(k)};
 useEffect(()=>{eyeApi<Hotel[]>('/hotels').then(h=>{setHotels(h);if(!canSeeAll&&h[0])setHotel(h[0].code)})},[]);
 useEffect(()=>{if(hotel)load().catch(()=>{})},[hotel]);
 const visible=useMemo(()=>reviews.filter(r=>(r.text+' '+(r.room||'')+' '+r.hotel+' '+r.tags.map(t=>t.category).join(' ')).toLowerCase().includes(query.toLowerCase())),[reviews,query]);
 const rated=visible.filter(r=>r.rating!==null); const avg=rated.length?rated.reduce((a,r)=>a+(r.rating||0),0)/rated.length:0;
 async function upload(files:FileList|null){if(!files?.length||!hotel||hotel==='all'){setMessage('Seleziona prima un singolo hotel.');return}setBusy(true);setMessage('');const body=new FormData();Array.from(files).forEach(f=>body.append('files',f));try{const res:any=await eyeApi(`/reviews/import/${hotel}`,{method:'POST',body});setMessage(`${res.imported} recensioni importate${res.errors?.length?` · ${res.errors.length} file/blocchi da verificare`:''}`);await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false);if(input.current)input.current.value=''}}
 const card=(title:string,items:any[],type:'room'|'service',bad=false)=><article className="panel"><div className="panel-title"><h2>{bad?<TriangleAlert size={18}/>:<Trophy size={18}/>} {title}</h2></div>{items.length?<ol className="ranking-list">{items.map((x,i)=><li key={`${type}-${i}-${x.room||x.service}`}><b>{i+1}. {type==='room'?`Camera ${x.room}`:x.service}</b><span>{type==='room'?`${x.hotel} · voto ${x.rating} · ${x.reviews} recensioni`:`${x.mentions} menzioni · +${x.positive}/-${x.negative}`}</span></li>)}</ol>:<div className="empty"><span>Nessun dato sufficiente.</span></div>}</article>;
 return <><PageHeader title="Recensioni" subtitle="Tre sezioni hotel separate; Supremo e Sviluppatore possono confrontarle tutte"><label className="global-search review-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca mentre scrivi…"/></label></PageHeader>
 <section className="hotel-selector">{canSeeAll&&<button className={hotel==='all'?'active':''} onClick={()=>setHotel('all')}>Tutti gli hotel</button>}{hotels.map(h=><button key={h.code} className={hotel===h.code?'active':''} onClick={()=>setHotel(h.code)}>{h.name}</button>)}</section>
 <section className="review-kpis"><article className="kpi"><MessageSquareText/><div><span>Recensioni</span><strong>{visible.length}</strong><small>{selected?.name||'Tutti gli hotel'}</small></div></article><article className="kpi"><Star/><div><span>Valutazione media</span><strong>{avg?avg.toFixed(2):'—'}</strong><small>periodo disponibile</small></div></article><article className="kpi"><UploadCloud/><div><span>Caricamento</span><strong>{hotel==='all'?'—':'MSG/EML/TXT'}</strong><small>prima scegli l'hotel, poi carichi i file</small></div></article></section>
 <section className="panel"><div className="panel-title"><h2>Carica recensioni · {selected?.name||'seleziona un hotel'}</h2></div><p>Un singolo file Outlook può contenere più recensioni: Eye Supremo le separa e le salva tutte nell'hotel selezionato.</p><button className="primary-btn" disabled={busy||!hotel||hotel==='all'} onClick={()=>input.current?.click()}><UploadCloud/>{busy?'Importazione…':'Carica file di posta'}</button><input ref={input} hidden multiple type="file" accept=".msg,.eml,.txt" onChange={e=>upload(e.target.files)}/>{message&&<p>{message}</p>}</section>
 <section className="reviews-layout"><div>{card('Top 5 camere migliori',rank.best_rooms,'room')}{card('Top 5 camere peggiori',rank.worst_rooms,'room',true)}</div><div>{card('Top 5 servizi migliori',rank.best_services,'service')}{card('Top 5 servizi peggiori',rank.worst_services,'service',true)}</div></section>
 <section className="panel reviews-panel"><div className="panel-title"><h2>Recensioni</h2><Status tone="ok">{visible.length} risultati</Status></div><div className="review-list">{visible.map(r=><article className="review-row" key={r.id}><div className="review-body"><div className="review-meta"><b>{r.hotel}{r.room?` · Camera ${r.room}`:''}</b><span>{r.source||'import'} · {r.date}</span></div><div className="stars">{r.rating!==null?`${r.rating} ★`:'senza voto'}</div><p>{r.text}</p><div className="review-actions">{r.tags.map(t=><Status key={`${t.category}-${t.polarity}`} tone={t.polarity==='negative'?'warn':'ok'}>{t.category} · {t.polarity==='negative'?'−':'+'}</Status>)}</div></div></article>)}</div></section></>;
}
