import {useEffect,useMemo,useState} from 'react';
import {ArrowDownToLine,ArrowUpFromLine,Boxes,RefreshCw,Save,SlidersHorizontal} from 'lucide-react';
import {api,euro} from '../lib/api';
import {Empty,PageHeader,Status} from '../components/UI';
import './Warehouse.css';

type StockRow={product_id:number;product:string;category?:string|null;unit:string;stock:number;min_quantity:number;low_stock:boolean;tracking_enabled:boolean;movement_count:number;latest_unit_cost?:number|null};
type Movement={id:number;product_id:number;product?:string|null;movement_type:'in'|'out'|'adjustment';quantity:number;signed_quantity:number;unit:string;unit_cost?:number|null;note?:string|null;created_at:string};

export default function Warehouse(){
 const [stocks,setStocks]=useState<StockRow[]>();
 const [movements,setMovements]=useState<Movement[]>();
 const [error,setError]=useState('');
 const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({product_id:'',movement_type:'in',quantity:'1',unit:'pz',unit_cost:'',note:''});
 const [invoiceId,setInvoiceId]=useState('');
 const [thresholds,setThresholds]=useState<Record<number,string>>({});
 const load=async()=>{setError('');try{const [s,m]=await Promise.all([api<StockRow[]>('/warehouse/summary'),api<Movement[]>('/warehouse/movements?limit=100')]);setStocks(s);setMovements(m);setThresholds(Object.fromEntries(s.map(x=>[x.product_id,String(x.min_quantity)])));if(!form.product_id&&s[0])setForm(f=>({...f,product_id:String(s[0].product_id),unit:s[0].unit||'pz'}))}catch(e:any){setError(e.message||'Impossibile caricare il magazzino')}};
 useEffect(()=>{load()},[]);
 const lowCount=useMemo(()=>stocks?.filter(x=>x.low_stock).length||0,[stocks]);
 const trackedCount=useMemo(()=>stocks?.filter(x=>x.tracking_enabled).length||0,[stocks]);
 async function addMovement(){if(!form.product_id)return;setBusy(true);setError('');try{await api('/warehouse/movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,product_id:Number(form.product_id),quantity:Number(form.quantity),unit_cost:form.unit_cost===''?null:Number(form.unit_cost)})});setForm(f=>({...f,quantity:'1',unit_cost:'',note:''}));await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function loadInvoice(){if(!invoiceId)return;setBusy(true);setError('');try{const result:any=await api(`/warehouse/from-invoice/${Number(invoiceId)}`,{method:'POST'});alert(`Carico fattura completato: ${result.created} movimenti creati, ${result.skipped} righe saltate.`);setInvoiceId('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveThreshold(row:StockRow){setBusy(true);setError('');try{await api(`/warehouse/products/${row.product_id}/threshold`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({min_quantity:Number(thresholds[row.product_id]||0),enabled:true})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="warehouse-page">
  <PageHeader title="Magazzino" subtitle="Giacenze, movimenti, carichi da fattura e soglie minime"><button className="secondary-btn" onClick={load}><RefreshCw/>Aggiorna</button></PageHeader>
  {error&&<div className="warehouse-error">{error}</div>}
  <section className="warehouse-kpis"><article className="panel"><span>Prodotti tracciati</span><b>{trackedCount}</b></article><article className="panel"><span>Sotto scorta</span><b>{lowCount}</b></article><article className="panel"><span>Movimenti registrati</span><b>{movements?.length||0}</b></article></section>
  <section className="warehouse-actions">
   <article className="panel warehouse-form"><div className="panel-title"><h2>Nuovo movimento</h2><Boxes/></div><div className="warehouse-fields"><label>Prodotto<select value={form.product_id} onChange={e=>{const id=e.target.value;const row=stocks?.find(x=>x.product_id===Number(id));setForm({...form,product_id:id,unit:row?.unit||'pz'})}}><option value="">Seleziona…</option>{stocks?.map(x=><option key={x.product_id} value={x.product_id}>{x.product}</option>)}</select></label><label>Tipo<select value={form.movement_type} onChange={e=>setForm({...form,movement_type:e.target.value})}><option value="in">Entrata</option><option value="out">Uscita</option><option value="adjustment">Rettifica (+/-)</option></select></label><label>Quantità<input type="number" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unità<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Costo unitario<input type="number" step="0.01" value={form.unit_cost} onChange={e=>setForm({...form,unit_cost:e.target.value})} placeholder="opzionale"/></label><label className="wide">Nota<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Motivo del movimento"/></label></div><button className="primary-btn" disabled={busy||!form.product_id} onClick={addMovement}>{form.movement_type==='out'?<ArrowUpFromLine/>:<ArrowDownToLine/>}Registra movimento</button></article>
   <article className="panel warehouse-form"><div className="panel-title"><h2>Carico da fattura</h2><ArrowDownToLine/></div><p>Genera automaticamente entrate dalle righe fattura già collegate a prodotti canonici. Le righe già caricate non vengono duplicate.</p><label>ID fattura<input type="number" min="1" value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} placeholder="es. 125"/></label><button className="secondary-btn" disabled={busy||!invoiceId} onClick={loadInvoice}>Carica prodotti fattura</button></article>
  </section>
  <section className="panel list-panel"><div className="panel-title"><h2>Giacenze</h2><Status tone={lowCount?'warn':'ok'}>{lowCount?`${lowCount} sotto scorta`:'Scorte OK'}</Status></div>{stocks?.length?<div className="table-wrap"><table><thead><tr><th>Prodotto</th><th>Categoria</th><th>Giacenza</th><th>Ultimo costo</th><th>Soglia minima</th><th>Stato</th><th/></tr></thead><tbody>{stocks.map(row=><tr key={row.product_id}><td><b>{row.product}</b></td><td>{row.category||'—'}</td><td><b>{row.stock.toLocaleString('it-IT')} {row.unit}</b></td><td>{row.latest_unit_cost!=null?euro(row.latest_unit_cost):'—'}</td><td><div className="threshold-control"><input type="number" min="0" step="0.01" value={thresholds[row.product_id]??''} onChange={e=>setThresholds({...thresholds,[row.product_id]:e.target.value})}/><span>{row.unit}</span></div></td><td><Status tone={row.low_stock?'danger':row.tracking_enabled?'ok':'warn'}>{row.low_stock?'Sotto scorta':row.tracking_enabled?'Tracciato':'Soglia off'}</Status></td><td><button className="icon-btn" title="Salva soglia" onClick={()=>saveThreshold(row)}><Save size={16}/></button></td></tr>)}</tbody></table></div>:stocks?<Empty title="Nessuna giacenza" text="Crea prodotti e registra il primo movimento di magazzino."/>:<p>Caricamento…</p>}</section>
  <section className="panel list-panel"><div className="panel-title"><h2>Ultimi movimenti</h2><SlidersHorizontal/></div>{movements?.length?<div className="table-wrap"><table><thead><tr><th>Data</th><th>Prodotto</th><th>Tipo</th><th>Quantità</th><th>Costo</th><th>Nota</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString('it-IT')}</td><td><b>{m.product||`#${m.product_id}`}</b></td><td><Status tone={m.movement_type==='in'?'ok':m.movement_type==='out'?'danger':'warn'}>{m.movement_type==='in'?'Entrata':m.movement_type==='out'?'Uscita':'Rettifica'}</Status></td><td>{m.signed_quantity>0?'+':''}{m.signed_quantity.toLocaleString('it-IT')} {m.unit}</td><td>{m.unit_cost!=null?euro(m.unit_cost):'—'}</td><td>{m.note||'—'}</td></tr>)}</tbody></table></div>:movements?<Empty title="Nessun movimento" text="I movimenti di magazzino appariranno qui."/>:<p>Caricamento…</p>}</section>
 </div>;
}
